### ISSUE TITLE
Suppress stdout?

### ISSUE THREAD

**Issue by lessthanoptimal** [bsideup/jabel#39] opened 2020-08-16 03:13 UTC
Trying to cut down on compile time stdout messages to make errors easier to see. Is there a way to disable what Jabel prints, e.g.
```
Jabel: initialized. Enabled features: 
        - PRIVATE_SAFE_VARARGS
        - EFFECTIVELY_FINAL_VARIABLES_IN_TRY_WITH_RESOURCES
        - LOCAL_VARIABLE_TYPE_INFERENCE
        - SWITCH_EXPRESSION
        - VAR_SYNTAX_IMPLICIT_LAMBDAS
        - TEXT_BLOCKS
        - DIAMOND_WITH_ANONYMOUS_CLASS_CREATION
        - SWITCH_MULTIPLE_CASE_LABELS
        - SWITCH_RULE
```
If this feature already exists could you maybe add it to the example as a comment out line? Thanks!

**Comment by bsideup** [comment] 2020-08-16 07:20
Hi @lessthanoptimal,

this seems to be a duplicate of #8. Let's continue the conversation there.

**Closed by bsideup** 2020-08-16 07:20 UTC
